# Generated by Django 5.2 on 2026-04-06 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coffee_type', models.CharField(choices=[('ARABICA', 'Arabica'), ('ROBUSTA', 'Robusta'), ('EXCELSA', 'Excelsa'), ('LIBERICA', 'Liberica')], default='ARABICA', max_length=20)),
                ('origin', models.CharField(help_text='Specific farm, region, or estate name', max_length=255)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=10)),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
                'permissions': [('approve_batch', 'Can approve or reject batches')],
            },
        ),
    ]
