# Generated by Django 5.2 on 2026-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='customer_approved_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='manager_approved_transit',
            field=models.BooleanField(default=False),
        ),
    ]
